// src/helpers/countryFilterHelper.test.ts

import { filterByCountry } from '../helpers/countryFilterHelper';
import { House } from '../models/houseModel';

describe('filterByCountry', () => {
  it('should filter houses by country', () => {
    const mockHouses: House[] = [
      {
        _id: '1',
        listing_url: '',
        name: 'House 1',
        summary: '',
        space: '',
        description: '',
        neighborhood_overview: '',
        notes: '',
        transit: '',
        access: '',
        interaction: '',
        house_rules: '',
        property_type: '',
        room_type: '',
        bed_type: '',
        minimum_nights: '',
        maximum_nights: '',
        cancellation_policy: '',
        last_scraped: new Date(),
        calendar_last_scraped: new Date(),
        accommodates: 2,
        bedrooms: 1,
        beds: 1,
        number_of_reviews: 0,
        bathrooms: 1,
        amenities: [],
        price: 100,
        guests_included: 1,
        images: {
          thumbnail_url: '',
          medium_url: '',
          picture_url: '',
          xl_picture_url: '',
        },
        host: {
          host_id: '',
          host_url: '',
          host_name: '',
          host_location: '',
          host_about: '',
          host_thumbnail_url: '',
          host_picture_url: '',
          host_neighbourhood: '',
          host_is_superhost: false,
          host_has_profile_pic: false,
          host_identity_verified: false,
          host_listings_count: 0,
          host_total_listings_count: 0,
          host_verifications: [],
        },
        address: {
          street: '',
          suburb: '',
          government_area: '',
          market: '',
          country: 'USA',
          country_code: 'US',
          location: {
            type: 'Point',
            coordinates: [0, 0],
            is_location_exact: true,
          },
        },
        availability: {
          availability_30: 0,
          availability_60: 0,
          availability_90: 0,
          availability_365: 0,
        },
        review_scores: {},
        reviews: [],
      },
      {
        _id: '2',
        listing_url: '',
        name: 'House 2',
        summary: '',
        space: '',
        description: '',
        neighborhood_overview: '',
        notes: '',
        transit: '',
        access: '',
        interaction: '',
        house_rules: '',
        property_type: '',
        room_type: '',
        bed_type: '',
        minimum_nights: '',
        maximum_nights: '',
        cancellation_policy: '',
        last_scraped: new Date(),
        calendar_last_scraped: new Date(),
        accommodates: 2,
        bedrooms: 1,
        beds: 1,
        number_of_reviews: 0,
        bathrooms: 1,
        amenities: [],
        price: 100,
        guests_included: 1,
        images: {
          thumbnail_url: '',
          medium_url: '',
          picture_url: '',
          xl_picture_url: '',
        },
        host: {
          host_id: '',
          host_url: '',
          host_name: '',
          host_location: '',
          host_about: '',
          host_thumbnail_url: '',
          host_picture_url: '',
          host_neighbourhood: '',
          host_is_superhost: false,
          host_has_profile_pic: false,
          host_identity_verified: false,
          host_listings_count: 0,
          host_total_listings_count: 0,
          host_verifications: [],
        },
        address: {
          street: '',
          suburb: '',
          government_area: '',
          market: '',
          country: 'Brazil',
          country_code: 'BR',
          location: {
            type: 'Point',
            coordinates: [0, 0],
            is_location_exact: true,
          },
        },
        availability: {
          availability_30: 0,
          availability_60: 0,
          availability_90: 0,
          availability_365: 0,
        },
        review_scores: {},
        reviews: [],
      },
    ];

    const result = filterByCountry(mockHouses, 'Brazil');

    expect(result).toHaveLength(1);
    expect(result[0].address.country).toBe('Brazil');
  });
});
